# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js base image
FROM node:16-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application using TypeScript
RUN npm run build

# Use a smaller base image for production
FROM node:16-alpine AS production

# Set working directory
WORKDIR /app

# Copy the built application and node_modules from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules

# Set NODE_ENV to production
ENV NODE_ENV=production

# Command to run tests
CMD ["npm", "test"]
