# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Base image for building the application
FROM node:20-alpine AS builder

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy all the source files
COPY . .

# Install typescript globally for the build
RUN npm install -g typescript

# Build the project
RUN npx tsc

# Production image
FROM node:20-alpine

WORKDIR /app

# Copy the built files and node_modules from builder
COPY --from=builder /app /app

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["node", "dist/index.js"]
